/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dell' at '17-7-4 下午2:04' with Gradle 2.14
 *
 * @author dell, @date 17-7-4 下午2:04
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
